name: CI

on
  push
    branches: [main]
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest-large
    steps:
      - name: List repository files
        run: ls -la

      - name: Run the hello script
        run: bash scripts/hello.sh

      - uses: actions/checkout
