name: Version Pipeline

on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.make.outputs.version }}

    steps:
      - name: Make version
        id: make
        run: echo "version=1.0.$GITHUB_RUN_NUMBER" >> "$GITHUB_OUTPUT"

  consume:
    needs: generate
    runs-on: ubuntu-latest

    steps:
      - name: Use version
        run: echo "Version is ${{ needs.generate.outputs.version }}"

      - name: Fail if empty
        run: |
          if [ -z "${{ needs.generate.outputs.version }}" ]; then
            echo "version was empty"
            exit 1
          fi
