name: Q6 Reusable Workflow

on:
  workflow_call:
    inputs:
      target_env:
        description: Target deployment environment
        required: true
        type: string

jobs:
  greet-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run composite action
        id: greet
        uses: ./.github/actions/greet
        with:
          name: GitHub User
          env_name: ${{ inputs.target_env }}

      - name: Show greeting
        run: |
          echo "${{ steps.greet.outputs.greeting }}"

      - name: Fake deploy
        run: |
          echo "Deploying to ${{ inputs.target_env }}... done."
